"""extend product_status enum

Revision ID: 2e11755af14e
Revises: 48cfeed37ac7
Create Date: 2025-10-06 14:01:25.584675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e11755af14e'
down_revision: Union[str, Sequence[str], None] = '48cfeed37ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE product_status ADD VALUE 'deprecated' after 'archived'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
