"""add status enum to product

Revision ID: 48cfeed37ac7
Revises: e138d2e6069e
Create Date: 2025-10-06 13:50:43.704952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cfeed37ac7'
down_revision: Union[str, Sequence[str], None] = 'e138d2e6069e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    product_status = sa.Enum('draft', 'published', 'archived', name='product_status')
    product_status.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'products', sa.Column('status', sa.Enum('draft', 'published', 'archived',
         name='product_status'), server_default='draft', nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'status')
    op.execute("DROP TYPE IF EXISTS product_status CASCADE")
    # ### end Alembic commands ###
